### ISSUE TITLE
error in readme

### ISSUE THREAD

**Issue by gerald2545** [institut-de-genomique/BoardION#1]
the line 
`docker run -it -p 80:80 -v input/folder/:/usr/local/src/data:z -v stat/folder/:/usr/local/src/stat:z boardion:latest -d 600 -f 5 -p 80`
should be
`docker run -it -p 80:80 -v input/folder/:/usr/local/src/data:z -v stat/folder/:/usr/local/src/stat:z **rdbioseq/**boardion:latest -d 600 -f 5 -p 80`

otherwise the following error raises : 
`Unable to find image 'boardion:latest' locally`

**Comment by Actal** [comment]
Thanks it's corrected.
