### ISSUE TITLE
Can boardION work with gzipped summary files?

### ISSUE THREAD

**Issue by callumparr** [institut-de-genomique/BoardION#10]
I had got boardION on some test data from epi2melabs but when I try to mount my own data volume where I have sequencing summary files gzipped boardION did not work. 

I uncompressed the summary file and seems to work OK now. Is there a way to get this to work with compressed files. if also wanting to load up archived runs it would be good as they can get quite big for long runs.

**Comment by sengelen** [comment]
You are right the sequencing summary are getting bigger and bigger, so  it would be a good idea to allow BoardION to process gzip sequencing summary files, it is not the case actually.
