### ISSUE TITLE
How to run recursively to find multiple runs 

### ISSUE THREAD

**Issue by callumparr** [institut-de-genomique/BoardION#11]
How do we get the docker container to find multiple runs? Do the sequencing summary files need to be first collated into one directory? Or is there a way to get it to search through subfolders?

**Comment by sengelen** [comment]
All the sequencing summary files should be directly (not in subfolder) in the input directory of the docker. Here we name the seq_sum files with the flowcell codes. If you want to see your runs as ended you have to also add the final_summary.txt files generated by the sequencer at the end of the runs.

**Comment by callumparr** [comment]
Would symlinks be OK?
