### ISSUE TITLE
cannot access Run/Sequencing overview menus due to javascript error

### ISSUE THREAD

**Issue by gerald2545** [institut-de-genomique/BoardION#5]
I compiled the preproccessing script in the container, generated the stats files...but no luck, I can't access them...
something I'm doing wrong?

![GIF](https://user-images.githubusercontent.com/10177830/84894485-342fea00-b0a1-11ea-91a3-6bb48b835284.gif)

**Comment by Actal** [comment]
On your image, the application is grayed out, this means that the application does not work anymore, hence its inaccessibility.
How did you execute it?

**Comment by gerald2545** [comment]
I followed the readme :  
docker run -it -p 80:80 -v C:\temp\boulot\boardion\input:/usr/local/src/data:z -v C:\temp\boulot\boardion\stat:/usr/local/src/stat:z rdbioseq/boardion -d 600 -f 5 -p 80

the application is grayed out as soon as I access it on localhost

**Comment by Actal** [comment]
can you add this option and tell me if there are any errors inside the logs/folder
-v /logs/folder:/usr/local/src/logs/:z

**Comment by gerald2545** [comment]
there is only the preprocess.log file
if it's easier, I can share my screen with you. Tell me if it would be OK for you and if you have some time this afternoon

**Comment by Actal** [comment]
I have fix it in the last version, could you confirm?

**Comment by gerald2545** [comment]
thanks,
OK I download it now

**Comment by gerald2545** [comment]
OK, I confirm the bug is corrected (if only one run is present in stat folder, and this run is not completed) with the last version
